sudo: required
dist: xenial
addons:
  apt:
    packages:
    - bsdtar
    - curl
    - zsync
services:
- docker

env:
  - RECIPE=eclipse

script:
- bash travis.sh $RECIPE
- find out/ -name "*.AppImage" -exec bash -e bintray.sh {} \; 

notifications:
  email: false
