#!/bin/bash -x

# In this case, the upstream project seems to already
# provide binaries that are supposed to run everywhere,
# so we merely package these as an AppImage

set +e

URL="https://github.com/fusion809/atom-custom/releases/download/v1.10.0/atom-1.10.0-amd64.deb"
echo $URL

APP=atom-bleeding

# get the desktop file
mkdir -p ./$APP/$APP.AppDir/usr/bin
cp ./atom.desktop ./$APP/$APP.AppDir

cd ./$APP

wget -c --trust-server-names "$URL"

cd $APP.AppDir/
dpkg -x ../atom*deb* .

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppRun" # (64-bit)
chmod a+x ./AppRun

# Move icon into place so that AppImageAssistant finds them
cp ./usr/share/pixmaps/atom.png .

# TODO: Get appdata
# mkdir -p ./usr/share/metainfo/
# wget -q "..." -O ./usr/share/metainfo/atom.appdata.xml

# Remove launcher and move in place
# TODO: Replace this by something cleaner
rm usr/bin/atom
mv usr/share/atom/* usr/bin/

# Add desktop integration
XAPP=atom
wget -O ./usr/bin/$XAPP.wrapper https://raw.githubusercontent.com/probonopd/AppImageKit/master/desktopintegration
chmod a+x ./usr/bin/$XAPP.wrapper

# Figure out $VERSION
VERSION=$(grep -r "atom@" ./usr/share/doc/atom/copyright | cut -d " " -f 2 | cut -d "@" -f 2)
echo $VERSION

# Go out of AppImage
cd ..

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
mkdir -p ../out
rm ../out/$APP"-"$VERSION"-x86_64.AppImage" || true
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION"-x86_64.AppImage"
