#!/bin/bash

# Exit on errors
set -e

################################### Get Dependencies ###################################
yum install -y git gcc gcc-c++ xz libtool make bzip2 perl wget            # base building tools
yum install -y squashfs-tools fuse fuse-devel fuse-libs fuseiso           # tools for building and using AppImageKit
yum install -y yum-utils epel-release                                     # yum-utils provides yum-builddep;
yum install -y gtk2-devel clang-devel cmake hunspell-devel libssh-devel \
               lldb-devel sqlite-devel wxGTK3-devel

ln -sf /usr/bin/wx-config-3.0 /usr/bin/wx-config

################################ Determine CodeLite version #################################
CODELITE_VERSION=$(curl -sL https://github.com/eranif/codelite/releases | grep ".tar.gz" | head -n 1 | cut -d '"' -f 2 | cut -d '/' -f 6 | sed 's|.tar.gz||g')

# Get codelite and build it
curl -sL https://github.com/eranif/codelite/archive/$CODELITE_VERSION.tar.gz | tar xz --transform="s/codelite-${CODELITE_VERSION}/codelite/"
cd codelite
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make
make install DESTDIR=/AppDir
cd ../..

############## Compilation and installation succeeded ##############

cd /AppDir/

cp ./usr/share/applications/codelite.desktop .
cp ./usr/share/icons/hicolor/256x256/apps/codelite.png .

# Strip executables; greatly reduces AppImage size
find . -type f -executable -exec strip {} \;

# Copy dependency libraries
mkdir -p ./usr/lib
ldd usr/bin/codelite | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./usr/lib || true

# Delete blacklisted files; TODO: Move to a library function
BLACKLISTED_FILES=$(curl -sL https://github.com/fusion809/AppImages/raw/master/excludelist | sed '/^\s*$/d' | sed '/^#.*$/d')
for FILE in $BLACKLISTED_FILES ; do
  FOUND=$(find . -type f -name "${FILE}" 2>/dev/null)
  if [ ! -z "$FOUND" ] ; then
    echo "Deleting blacklisted ${FOUND}"
    rm -f "${FOUND}"
  fi
done

curl -OL "https://github.com/probonopd/AppImageKit/releases/download/5/AppRun" # (64-bit)
chmod a+x ./AppRun

# Add desktop integration
XAPP=codelite
curl -L https://raw.githubusercontent.com/probonopd/AppImageKit/master/desktopintegration > ./usr/bin/$XAPP.wrapper
chmod a+x ./usr/bin/$XAPP.wrapper
sed -i -e "s|Exec=$XAPP|Exec=$XAPP.wrapper|g" $XAPP.desktop

# Go out of AppImage
cd ..
