#!/bin/bash

# Exit on errors
set -e

################################### Get Dependencies ###################################
yum install -y git gcc gcc-c++ xz libtool make bzip2 perl wget            # base building tools
yum install -y squashfs-tools fuse fuse-devel fuse-libs fuseiso           # tools for building and using AppImageKit
yum install -y yum-utils epel-release                                     # yum-utils provides yum-builddep;

yum-builddep -y gnucash

################################ Determine GNU Cash version #################################
GNUCASH_VERSION=$(wget -q https://sourceforge.net/projects/gnucash/files/gnucash%20%28stable%29/ -O - | grep gnucash | grep "[0-9]" | grep "\.[0-9]" | head -n 1 | cut -d '"' -f 4 | cut -d ':' -f 1 | cut -d '/' -f 4 | sed 's/gnucash\-//g' | sed 's/\.tar\.bz2//g')

# Get GNU Cash and build it
curl -sL https://sourceforge.net/projects/gnucash/files/gnucash%20%28stable%29/$GNUCASH_VERSION/gnucash-$GNUCASH_VERSION.tar.bz2 | tar xj --transform="s/gnucash-${GNUCASH_VERSION}/gnucash/"
cd gnucash
./configure --prefix=/AppDir/usr
make
make install
cd ..

############## Compilation and installation succeeded ##############

cd /AppDir/

cp ./usr/share/applications/gnucash.desktop .
cp ./usr/share/icons/hicolor/scalable/apps/gnucash-icon.svg .

# Strip executables; greatly reduces AppImage size
find . -type f -executable -exec strip {} \;

# Copy dependency libraries
mkdir -p ./usr/lib
ldd usr/bin/gnucash | grep "=>" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./usr/lib || true

# Delete blacklisted files; TODO: Move to a library function
BLACKLISTED_FILES=$(curl -sL https://github.com/fusion809/AppImages/raw/master/excludelist | sed '/^\s*$/d' | sed '/^#.*$/d')
for FILE in $BLACKLISTED_FILES ; do
  FOUND=$(find . -type f -name "${FILE}" 2>/dev/null)
  if [ ! -z "$FOUND" ] ; then
    echo "Deleting blacklisted ${FOUND}"
    rm -f "${FOUND}"
  fi
done

curl -OL "https://github.com/probonopd/AppImageKit/releases/download/5/AppRun" # (64-bit)
chmod a+x ./AppRun

# Add desktop integration
XAPP=gnucash
curl -L https://raw.githubusercontent.com/probonopd/AppImageKit/master/desktopintegration > ./usr/bin/$XAPP.wrapper
chmod a+x ./usr/bin/$XAPP.wrapper
sed -i -e "s|Exec=$XAPP|Exec=$XAPP.wrapper|g" $XAPP.desktop

# Go out of AppImage
cd ..
