#!/bin/bash
# Octave recipe

yum -y install wget git
wget -q https://github.com/probonopd/AppImages/raw/master/functions.sh -O ./functions.sh
. ./functions.sh

#begin
if [ ! -d AppImages ] ; then
  git clone https://github.com/probonopd/AppImages.git
fi
cd AppImages/
git_pull_rebase_helper
cd ..

yum -y install binutils fuse glibc-devel glib2-devel fuse-devel gcc zlib-devel libpng12 cmake

APP=Octave
mkdir -p /$APP/$APP.AppDir/
cd /$APP/

URL=https://ftp.gnu.org/gnu/octave/octave-4.2.0.tar.lz
VER1=4.2.0

yum -y install epel-release gcc-gfortran gcc-c++ pcre-devel blas-devel lapack-devel readline-devel fftw-devel zlib-devel \
gnuplot-devel qhull-devel glpk-devel curl-devel qrupdate-devel suitesparse-devel \
arpack-devel mesa-libGLU-devel mesa-libGL-devel tar mesa-libOSMesa-devel freetype-devel fontconfig-devel \
hdf5-devel gnuplot texinfo java-1.8.0-openjdk-devel fltk-devel qt-devel yum-utils xz \
gperf flex bison ghostscript texinfo-text texinfo-tex icoutils librsvg2 gl2ps-devel qscintilla-devel desktop-file-utils fuse-libs \
http://ftp.tu-chemnitz.de/pub/linux/dag/redhat/el6/en/x86_64/rpmforge/RPMS/lzip-1.15-1.el6.rf.x86_64.rpm

yum-builddep octave

wget http://ftpmirror.gnu.org/gcc/gcc-5.2.0/gcc-5.2.0.tar.bz2
tar xf gcc-5.2.0.tar.bz2

wget https://gmplib.org/download/gmp/gmp-6.0.0a.tar.xz
tar xf gmp-6.0.0a.tar.xz
mv gmp-6.0.0 gcc-5.2.0/gmp
cd gcc-5.2.0/gmp
./configure --prefix=/usr && make && make install
cd ../..

wget ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
tar xf mpc-1.0.3.tar.gz
mv mpc-1.0.3 gcc-5.2.0/mpc
cd gcc-5.2.0/mpc
./configure --prefix=/usr && make && make install
cd ../..

wget http://www.mpfr.org/mpfr-current/mpfr-3.1.5.tar.xz
tar xf mpfr-3.1.5.tar.xz
mv mpfr-3.1.5 gcc-5.2.0/mpfr
cd gcc-5.2.0/mpfr
./configure --prefix=/usr && make && make install
cd ../..

mkdir gcc-5.2.0/gcc-build && cd gcc-5.2.0/gcc-build

# I don't have root privilege, so install to a subdir in my home directory
../configure --prefix=$HOME/gcc5 \
             --disable-multilib \
             --enable-languages=c,c++ \
             --enable-libstdcxx-threads \
             --enable-libstdcxx-time \
             --enable-shared \
             --enable-__cxa_atexit \
             --disable-libunwind-exceptions \
             --disable-libada \
             --host x86_64-redhat-linux-gnu \
             --build x86_64-redhat-linux-gnu \
             --with-default-libstdcxx-abi=gcc4-compatible

# For clusters, you should request a compute node in slurm to do the compilation. Don't do these in head node
make -j4

make install

wget -c "$URL"
tar --lzip -xvf octave-*.tar.lz

cd octave-*

export CFLAGS="-O2"
export CXXFLAGS="-O2"

./configure --prefix=/usr
make
make install DESTDIR=/$APP/$APP.AppDir/

cd /$APP/$APP.AppDir/

# Copy in the indirect dependencies
copy_deps

#cp /$APP/octave-*/etc/icons/octave.desktop .
#sed -i 's|usr/local|usr|g' octave.desktop

#Desktop file
cat > ./octave.desktop <<EOF
[Desktop Entry]
Name=GNU Octave
Comment=Scientific Computing using GNU Octave
TryExec=octave
Exec=octave --force-gui %f
Icon=octave.png
Terminal=false
Type=Application
Categories=Education;Science;Math;
StartupNotify=false
MimeType=text/x-octave;text/x-matlab;
Keywords=science;math;matrix;numerical computation;plotting;
EOF

cp ./usr/share/icons/hicolor/256x256/apps/octave.png .

get_apprun

delete_blacklisted

#Get makeinfo inside
#cp $(which makeinfo) ./usr/bin

# Move libraries in place
mv lib64/* usr/lib && rm -r lib64/
mv ./usr/lib64/atlas/* usr/lib && rm -r ./usr/lib64/atlas/
mv ./usr/lib64/* usr/lib && rm -r ./usr/lib64/

# Remove developer stuff
rm -rf usr/include/
find . -name '*.la' -delete
find . -type f -executable -exec strip {} \; || true

# Patch absolute /usr away; make relative to usr/ inside the AppDir
find usr/ -type f -executable -exec sed -i -e "s|/usr|././|g" {} \;

GLIBC_NEEDED=$(glibc_needed)
VERSION=$VER1.glibc$GLIBC_NEEDED
echo $VERSION

get_desktopintegration octave

# Go out of AppImage
cd ..

ARCH=$(/bin/arch)

if [[ "$ARCH" = "x86_64" ]] ; then
	APPIMAGE=$APP"-"$VERSION"-x86_64.AppImage"
fi
if [[ "$ARCH" = "i686" ]] ; then
	APPIMAGE=$APP"-"$VERSION"-i386.AppImage"
fi

# Put this script into the AppImage for debugging
# FIXME: The follwing line does not work
# cp $(readlink --canonicalize $0) ./$APP.AppDir/$APP.recipe

mkdir -p ../out

rm -f ../out/*.AppImage || true

# Convert the AppDir into an AppImage
rm -rf $APPIMAGE
wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant ./$APP.AppDir/ ../out/$APPIMAGE

chmod a+rwx ../out/$APPIMAGE # So that we can edit the AppImage outside of the Docker container
