#!/bin/bash

# This is an example for packaging a Java application as an AppImage.
# This application comes with a JRE.

APP="eclipse-cpp"
VERSION=4.6.0
echo $VERSION

wget -c https://worldvectorlogo.com/logos/eclipse-11.svg
cp eclipse-11.svg $APP/$APP.AppDir/$APP.svg

mkdir -p $APP/$APP.AppDir/usr/bin

cd $APP/

wget -c "http://mirror.internode.on.net/pub/eclipse/technology/epp/downloads/release/neon/R/eclipse-cpp-neon-R-linux-gtk-x86_64.tar.gz"

cd $APP.AppDir/

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppRun" # (64-bit)
chmod a+x ./AppRun

bsdtar -xf ../eclipse-*.tar.gz -C usr
cp -r usr/eclipse/* usr/bin
rm -rf usr/eclipse

mv usr/bin/eclipse usr/bin/eclipse-cpp

cat > $APP.desktop <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=$APP
Icon=$APP
Exec=$APP.wrapper
Categories=Development;IDE;
Terminal=false
EOF

# Move out of $APPDIR
wget -O ./usr/bin/$APP.wrapper https://raw.githubusercontent.com/probonopd/AppImageKit/master/desktopintegration
chmod a+x ./usr/bin/$APP.wrapper
cd ..

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
mkdir -p ../out
rm ../out/$APP"-"$VERSION"-x86_64.AppImage" || true
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION"-x86_64.AppImage"
