#!/bin/bash

# This is not working yet, look at other recipes for examples

APP="eclipse-cpp"
LOWERAPP=${APP//-cpp/}
VERSION=4.6.0 # FIXME: Do not hardcode the version number

mkdir -p $APP/$APP.AppDir/usr/bin

cd $APP/

wget -q https://github.com/probonopd/AppImages/raw/master/functions.sh -O ./functions.sh
. ./functions.sh

# FIXME: Never hardcode download links in this way; get from "official" URL
wget -c "http://mirror.internode.on.net/pub/$LOWERAPP/technology/epp/downloads/release/neon/R/$LOWERAPP-cpp-neon-R-linux-gtk-x86_64.tar.gz"

generate_status

echo "deb http://archive.ubuntu.com/ubuntu/ trusty main universe
" > sources.list

apt-get $OPTIONS update

URLS=$(apt-get $OPTIONS -y install --print-uris eclipse | cut -d "'" -f 2 | grep -e "^http" | grep -v "eclipse")

wget -c $URLS

cd $APP.AppDir/

find ../*.deb -exec dpkg -x {} . \; || true

get_apprun

tar -xzf ../$LOWERAPP-*.tar.gz -C usr
cp -r usr/$LOWERAPP/* usr/bin
rm -rf usr/$LOWERAPP

mv usr/bin/eclipse usr/bin/eclipse-cpp

cat > $APP.desktop <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=Eclipse
Icon=$LAPP
Exec=$APP.wrapper
Categories=Development;IDE;C;C++
Terminal=false
EOF

cp usr/bin/plugins/org.eclipse.epp.package.cpp_*/eclipse256.png $LOWERAPP.png

find usr \
  -or -name "*.bat" -exec rm '{}' \; \
  -or -name "mac*.png" -exec rm '{}' \; \
  -or -name "win*.png" -exec rm '{}' \; \
  -or -name "eclipse*.gif" -exec rm '{}' +

get_desktopintegration $APP

cd .. # Move out of the AppDir

generate_appimage
