#!/bin/bash

# This is an example for packaging a Java application as an AppImage.
# This application comes with a JRE.

APP=Eclipse
LOWERAPP=${APP,,}

cp icon.xpm $APP/$APP.AppDir/eclipse.xpm

mkdir -p $APP/$APP.AppDir/usr/bin
mkdir -p $APP/$APP.AppDir/usr/lib

cd $APP/

wget -c "http://mirror.internode.on.net/pub/eclipse/technology/epp/downloads/release/neon/R/eclipse-cpp-neon-R-linux-gtk-x86_64.tar.gz"

cd $APP.AppDir/

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppRun" # (64-bit)
chmod a+x ./AppRun

bsdtar -xf ../eclipse-*.tar.gz -C usr/lib

cat > $LOWERAPP.desktop <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=$APP
Icon=$LOWERAPP
Exec=$LOWERAPP
Categories=Development;IDE;
Terminal=false
EOF

cat > usr/bin/$LOWERAPP <<EOF
#!/bin/sh
export ECLIPSE_HOME=../lib/eclipse
exec ${ECLIPSE_HOME}/eclipse "$@"
EOF

VERSION=4.6.0
echo $VERSION

# Do not add desktop integration since it comes with its own

cd .. # Go out of AppDir

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
mkdir -p ../out
rm ../out/$APP"-"$VERSION"-x86_64.AppImage" || true
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION"-x86_64.AppImage"
