#!/bin/bash

# In this case the upstream project seems to already
# provide binaries that are supposed to run everywhere,
# so we merely package these as an AppImage

set +e

APP=OpenRA
LOWERAPP=${APP,,}
VERSION="release-20161015"
URL="https://github.com/OpenRA/OpenRA/releases/download/${VERSION}/openra_${VERSION//-/.}_all.deb"
rm -rf ./$APP/$APP.AppDir

mkdir -p ./$APP/$APP.AppDir/usr/bin
mkdir -p ./$APP/$APP.AppDir/usr/lib
cd ./$APP

wget -c "$URL"

wget -q https://github.com/probonopd/AppImages/raw/master/functions.sh -O ./functions.sh
. ./functions.sh

generate_status

echo "deb http://archive.ubuntu.com/ubuntu/ trusty main universe
" > sources.list

apt-get $OPTIONS update

URLS=$(apt-get $OPTIONS -y install --print-uris libopenal1 libmono-corlib2.0-cil mono-runtime libmono-system-core4.0-cil libmono-system-drawing4.0-cil libmono-system-data4.0-cil libmono-system-numerics4.0-cil libmono-system-runtime-serialization4.0-cil libmono-system-xml-linq4.0-cil libmono-i18n4.0-all libfreetype6 libc6 libasound2 libgl1-mesa-glx libgl1-mesa-dri xdg-utils zenity liblua5.1-0 | cut -d "'" -f 2 | grep -e "^http" )

printf "URLS is \n:$URLS"
wget -c $URLS

wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppRun" # (64-bit)
chmod a+x ./AppRun

cd ./$APP.AppDir/

find ../*.deb -exec dpkg -x {} . \; || true

cd usr/games
echo '#!/bin/sh
cd "././/lib/openra"
mono --debug OpenRA.Game.exe "$@"
if [ $? != 0 -a $? != 1 ]
then
ZENITY=`which zenity` || echo "OpenRA needs zenity installed to display a graphical error dialog. See ~/.openra. for log files."
$ZENITY --question --title "OpenRA" --text "OpenRA has encountered a fatal error.
Log Files are available in ~/.openra." --ok-label "Quit" --cancel-label "View FAQ" || xdg-open https://github.com/OpenRA/OpenRA/wiki/FAQ
exit 1
fi' > openra
chmod +x openra
cd ../../lib/openra
ln -sf ../../usr/bin/mono-sgen mono
cd ../..

get_desktop
get_icon
get_apprun

rm -rf ./etc/ ./home/ || true

# patch_usr
# Patching only the executable files seems not to be enough for some apps
find usr/ -type f -exec sed -i -e "s|/usr|././|g" {} \;


wget -O ./usr/bin/$LOWERAPP.wrapper https://raw.githubusercontent.com/probonopd/AppImageKit/master/desktopintegration
chmod a+x ./usr/bin/$LOWERAPP.wrapper

cd ..
wget -c "https://github.com/probonopd/AppImageKit/releases/download/5/AppImageAssistant" # (64-bit)
chmod a+x ./AppImageAssistant
mkdir -p ../out
if [[ -f ../out/$APP"-"$VERSION"-x86_64.AppImage" ]]; then
  rm ../out/$APP"-"$VERSION"-x86_64.AppImage" || true
fi
./AppImageAssistant ./$APP.AppDir/ ../out/$APP"-"$VERSION"-x86_64.AppImage"
